_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.8.18
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 15
                - 16
                - 23
                - 55
            "4": 3.8.18
            "5": 0.19.7
            "8":
                - 3
                - 5
            "12": 0.19.7
            "13": windows-amd64
architecture:
    value: CNN
dataset_id:
    value: peds-0192
infra:
    value: AWS
learning_rate:
    value: 0.01
momentum:
    value: 0.2
