# @package _global_

env:
  name: BipedalWalker-v3
  demo: BipedalWalker-v3_expert_trajs
  replay_mem: 1e6
  initial_mem: 10000
  eps_steps: 1000
  eps_window: 100
  learn_steps: 1e5
  eval_interval: 1e3

expert:
  demos: 64
  subsample_freq: 20

eval:
  policy: 
  threshold: 500
  eps: 10

agent:
  name: sac
  class: agent.sac.SAC
  init_temp: 0.001
  critic_lr: 0.0001
  actor_lr: 3e-5
  critic_betas: [0.9, 0.999]
  learn_temp: false
  critic_target_update_frequency: 4
  critic_tau: 0.005

train:
  use_target: true
  soft_update: true
  batch: 256

q_net:
  _target_: agent.sac_models.SingleQCritic

log_interval: 500   
num_actor_updates: 1
